phases:
  install:
    commands:
      - echo not needed for now     
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo build started o `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - package.json
    - node_modules/*
    - public/*
    - src/*